# Generated by Django 3.0.3 on 2020-03-19 11:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.DateField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('company', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('fullstack', 'Fullstack')], default='intern', max_length=50)),
                ('skill', models.CharField(choices=[('c++', 'Cplusplus'), ('c', 'C'), ('java', 'Java'), ('python', 'Python'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('sql', 'Sql'), ('git', 'Git'), ('django', 'Django'), ('android', 'Android'), ('ios', 'Ios'), ('nothing', 'Nothing')], default='nothing', max_length=50)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('c++', 'Cplusplus'), ('c', 'C'), ('java', 'Java'), ('python', 'Python'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('sql', 'Sql'), ('git', 'Git'), ('django', 'Django'), ('android', 'Android'), ('ios', 'Ios'), ('nothing', 'Nothing')], default='nothing', max_length=50)),
                ('position', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('fullstack', 'Fullstack')], default='intern', max_length=50)),
                ('salary', models.DecimalField(decimal_places=5, default=Decimal('0.01'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('c++', 'Cplusplus'), ('c', 'C'), ('java', 'Java'), ('python', 'Python'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('sql', 'Sql'), ('git', 'Git'), ('django', 'Django'), ('android', 'Android'), ('ios', 'Ios'), ('nothing', 'Nothing')], default='nothing', max_length=50)),
                ('position', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('fullstack', 'Fullstack')], default='intern', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Employee')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.DateField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('rating', models.IntegerField(choices=[(1, 'Aaa'), (2, 'Aa'), (3, 'A'), (4, 'Bbb'), (5, 'Bb'), (6, 'B')], null=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('nsd', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.Interview')),
            ],
            options={
                'verbose_name': 'HR',
                'verbose_name_plural': 'HRs',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.DateField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('company', models.CharField(max_length=50)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.Offer')),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.Resume'),
        ),
    ]
